### ISSUE TITLE
[Bug]: error on startup

### ISSUE THREAD

**Issue by OshekharO** [Pool-Of-Tears/Myne#161]
### Steps to reproduce

1. Open application
2. Click get started
3. Error occurred

### Expected behaviour

It should have opened without errors

### Actual behaviour

Unexpectedly crashed

### Device name

Poco f1

### Android version

Android 13.1

### Myne version

3.5.1

### Device logs

Build version: 3.5.1 
Current date: 2024-04-27 18:42:32 
Device: Xiaomi POCOPHONE F1 
OS version: Android 13 (SDK 33) 
 
Stack trace:  
java.lang.NullPointerException
	at com.starry.myne.ui.screens.home.viewmodels.HomeViewModel.d(Unknown Source:77)
	at O3.g.w(Unknown Source:12)
	at o4.a.p(Unknown Source:8)
	at S5.G.run(Unknown Source:112)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7927)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
	Suppressed: X5.g: [t0{Cancelling}@2492af, Dispatchers.Main.immediate]

**Comment by starry-shivam** [comment]
Thanks for reporting the issue, are you using some kind of firewall/DNS which cold be blocking the network request?

**Comment by starry-shivam** [comment]
Anyhow, it shouldn't crash due to that.
