### ISSUE TITLE
NPE when downloding "Tractatus Logico-Philosophicus" 

### ISSUE THREAD

**Issue by k3b** [Pool-Of-Tears/Myne#42]
When i try to download "Tractatus Logico-Philosophicus" I get a null pointer exception.

Device Android-10
Manufacturer LG

App 1.4.0 (2023-03-11) downloaded from izzy repository

Also reproducable with current sourcecode (as of 2023-03-15) build from https://github.com/Pool-Of-Tears/Myne/

<pre>
reason: in BookDownloader.kt:51         val uri = Uri.parse(book.formats.applicationepubzip)
applicationepubzip is null
</pre>
------

Book(id=5740, title=Tractatus Logico-Philosophicus, authors=[Author(name=Wittgenstein, Ludwig, birthYear=1889, deathYear=1951)], translators=[Translator(name=Ogden, C. K. (Charles Kay), birthYear=1889, deathYear=1957)], subjects=[Language and languages -- Philosophy, Logic, Symbolic and mathematical], bookshelves=[DE Sachbuch, Mathematics, Philosophy], languages=[de, en], copyright=false, mediaType=Text, formats=Formats(textplain=null, applicationxMobipocketEbook=null, texthtml=null, applicationoctetStream=https://www.gutenberg.org/files/5740/5740-page-images/f0001.png, textplainCharsetusAscii=null, applicationepubzip=null, imagejpeg=https://www.gutenberg.org/cache/epub/5740/pg5740.cover.medium.jpg, applicationrdfxml=https://www.gutenberg.org/ebooks/5740.rdf, texthtmlCharsetiso88591=null, texthtmlCharsetutf8=null, textplainCharsetutf8=null, textplainCharsetiso88591=null), downloadCount=4386)

---

Logcat

<pre>
2023-03-15 13:03:40.331 13563-13563 MainActivity::Storage   com.starry.myne.dev                  D  Permission is granted
2023-03-15 13:03:40.366 13563-13563 AndroidRuntime          com.starry.myne.dev                  E  FATAL EXCEPTION: main
Process: com.starry.myne.dev, PID: 13563
java.lang.NullPointerException: uriString
	at android.net.Uri$StringUri.<init>(Uri.java:496)
	at android.net.Uri$StringUri.<init>(Uri.java:486)
	at android.net.Uri.parse(Uri.java:458)
	at com.starry.myne.others.BookDownloader.downloadBook(BookDownloader.kt:51)
	at com.starry.myne.ui.screens.home.viewmodels.BookDetailViewModel.downloadBook(BookDetailViewModel.kt:82)
	at com.starry.myne.ui.screens.home.composables.BookDetailScreenKt$BookDetailScreen$2$1$4$3.invoke(BookDetailScreen.kt:336)
	at com.starry.myne.ui.screens.home.composables.BookDetailScreenKt$BookDetailScreen$2$1$4$3.invoke(BookDetailScreen.kt:300)
	at com.starry.myne.ui.screens.home.composables.BookDetailScreenKt$MiddleBar$1$3$1.invoke(BookDetailScreen.kt:522)
	at com.starry.myne.ui.screens.home.composables.BookDetailScreenKt$MiddleBar$1$3$1.invoke(BookDetailScreen.kt:522)
	at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$1$2.invoke-k-4lQ0M(Clickable.kt:167)
	at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$1$2.invoke(Clickable.kt:156)
	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1.invokeSuspend(TapGestureDetector.kt:255)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.kt:566)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.dispatchPointerEvent(SuspendingPointerInputFilter.kt:456)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:469)
	at androidx.compose.ui.node.BackwardsCompatNode.onPointerEvent-H0pRuoY(BackwardsCompatNode.kt:374)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:314)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:301)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:301)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:301)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:301)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:301)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:301)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:301)
	at androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(HitPathTracker.kt:183)
	at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:102)
	at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(PointerInputEventProcessor.kt:98)
	at androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1357)
	at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1303)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(AndroidComposeView.android.kt:1242)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3142)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2834)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3142)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2834)
2023-03-15 13:03:40.370 13563-13563 AndroidRuntime          com.starry.myne.dev                  E  	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3142)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2834)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3142)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2834)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3142)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2834)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3142)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2834)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:495)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1868)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4022)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:70)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:453)
	at android.view.View.dispatchPointerEvent(View.java:14261)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5919)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5722)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5169)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5222)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5188)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5196)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5169)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5222)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5188)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5344)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5196)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5401)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5169)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5222)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5188)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5196)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5169)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8018)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7985)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7946)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8172)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:189)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:336)
	at android.os.Looper.loop(Looper.java:174)
	at android.app.ActivityThread.main(ActivityThread.java:7615)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@1411474, androidx.compose.runtime.BroadcastFrameClock@2a93d9d, StandaloneCoroutine{Cancelling}@7434212, AndroidUiDispatcher@1b0cde3]

</pre>

**Comment by starry-shivam** [comment]
Thanks for creating such a detailed bug report, I'll try to investigate and fix it soon!

**Comment by starry-shivam** [comment]
It seems like there are no epub files available yet, for a few books ig I'll just filter them out from the app for now
