### ISSUE TITLE
[crash report] crash while trying to open ebook from kvaesitso launcher 

### ISSUE THREAD

**Issue by zoroya1** [Pool-Of-Tears/Myne#73]
Build version: 2.4.0 
Current date: 2023-08-15 22:30:01 
Device: OnePlus GM1911 
OS version: Android 13 (SDK 33) 
 
Stack trace:  
java.io.FileNotFoundException: /external_files/Books/meditations emperor-of rome marcus aurelius hays.epub: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:574)
	at java.io.FileInputStream.<init>(FileInputStream.java:160)
	at java.io.FileInputStream.<init>(FileInputStream.java:115)
	at z7.d$b.k(Unknown Source:7)
	at z7.d$b.r0(Unknown Source:12)
	at ac.x.v(Unknown Source:4)
	at a4.a.q0(Unknown Source:71)
	at z7.d.a(Unknown Source:67)
	at q8.f.k(Unknown Source:39)
	at m9.a.q(Unknown Source:8)
	at lc.k0.run(Unknown Source:100)
	at kotlinx.coroutines.internal.f.run(Unknown Source:11)
	at kotlinx.coroutines.scheduling.j.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.a$a.run(Unknown Source:78)
	Suppressed: b5.e: [s1{Cancelling}@4a088b5, Dispatchers.IO]
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7808)
	at libcore.io.IoBridge.open(IoBridge.java:560)
	... 13 more

When I try to open an ebook from the launcher, myne crashes instantly.

**Comment by starry-shivam** [comment]
will try to investigate when i have time, ty for reporting.
